name: Trigger AzDO PR pipeline

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  trigger-azdo-tests:
    runs-on: ubuntu-latest
    environment: ni-dev
    steps:
      - name: Trigger Main
        uses: Azure/pipelines@v1.2
        with:
          azure-devops-project-url: "https://dev.azure.com/ni/Users"
          azure-pipeline-name: "cfuentes-pipelines"
          azure-devops-token: ${{ secrets.CFC_TOKEN }}
          azure-pipeline-variables: '{"PR_BRANCH": "${{ github.ref_name }}"}'
